//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLMDSAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sappwd:80/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_CARSY" +
            "S_CQ&receiverParty=&receiverService=&interface=SI_pd_info_upload_req&interfaceNa" +
            "mespace=urn%3ANDPaper.com%3AI_QM%3Apd_info_upload")]
        public string JLMDSAP_sappwd_BS_CARSYS_CQ_SI_pd_info_upload_req {
            get {
                return ((string)(this["JLMDSAP_sappwd_BS_CARSYS_CQ_SI_pd_info_upload_req"]));
            }
        }
    }
}
