//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEWE.CarManagement.Entity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201105061557\\SQL2005;Initial Catalog=EMEWECAR2012-7-02;Integrated " +
            "Security=True")]
        public string EMEWECAR2012_7_02ConnectionString {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201211151110;Initial Catalog=EMEWECAR2012-7-02;Integrated Security" +
            "=True")]
        public string EMEWECAR2012_7_02ConnectionString1 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201211151110\\MSSQLSERVER2008;Initial Catalog=EMEWECAR2012-7-02;Per" +
            "sist Security Info=True;User ID=sa;Password=sa")]
        public string EMEWECAR2012_7_02ConnectionString2 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWECAR2012-7-02;Persist Securit" +
            "y Info=True;User ID=sa")]
        public string EMEWECAR2012_7_02ConnectionString3 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWECAR2012-7-02;Persist Securit" +
            "y Info=True;User ID=sa;Password=sa")]
        public string EMEWECAR2012_7_02ConnectionString4 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWECAR2012-7-02;User ID=sa")]
        public string EMEWECAR2012_7_02ConnectionString5 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWEQC;User ID=sa;Password=sa")]
        public string EMEWEQCConnectionString {
            get {
                return ((string)(this["EMEWEQCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWECAR2012-7-02;User ID=sa;Pass" +
            "word=sa")]
        public string EMEWECAR2012_7_02ConnectionString6 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.185.1.181\\SA;Initial Catalog=EMEWECAR2012-7-02;User ID=sa;Password" +
            "=888888")]
        public string EMEWECAR2012_7_02ConnectionString7 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.185.1.181\\sa;Initial Catalog=EMEWECAR2012-7-02;User ID=sa;Password" +
            "=888888")]
        public string EMEWECAR2012_7_02ConnectionString8 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.185.1.181\\SA;Initial Catalog=EMEWECAR2012-7-02;Persist Security In" +
            "fo=True;User ID=sa;Password=888888")]
        public string EMEWECAR2012_7_02ConnectionString9 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=G4PTZSWNYTESLKX\\SQLEXPRESS;Initial Catalog=EMEWECAR2012-7-02;User ID=" +
            "sa;Password=sa")]
        public string EMEWECAR2012_7_02ConnectionString10 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.103;Initial Catalog=EMEWECAR2012-7-02;User ID=sa;Password=s" +
            "a")]
        public string EMEWECAR2012_7_02ConnectionString11 {
            get {
                return ((string)(this["EMEWECAR2012_7_02ConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.185.1.181\\sa;Initial Catalog=EMEWECAR20130815;User ID=sa;Password=" +
            "888888")]
        public string EMEWECAR20130815ConnectionString {
            get {
                return ((string)(this["EMEWECAR20130815ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EMEWECAR20130815;Persist Security Info=True;User ID" +
            "=sa;Password=sa")]
        public string EMEWECAR20130815ConnectionString1 {
            get {
                return ((string)(this["EMEWECAR20130815ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.185.103.25;Initial Catalog=EMEWECAR20130815;User ID=sa;Password=88" +
            "8888")]
        public string EMEWECAR20130815ConnectionString2 {
            get {
                return ((string)(this["EMEWECAR20130815ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EMEWECAR20130815;User ID=sa;Password=sa")]
        public string EMEWECAR20130815ConnectionString3 {
            get {
                return ((string)(this["EMEWECAR20130815ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=42.51.7.113;Initial Catalog=CQNDCL;User ID=sa;Password=xiao1125ZUN")]
        public string CQNDCLConnectionString {
            get {
                return ((string)(this["CQNDCLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CQNDCL;User ID=sa;Password=sa")]
        public string CQNDCLConnectionString1 {
            get {
                return ((string)(this["CQNDCLConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.120;Initial Catalog=CQNDCL20180910;User ID=sa;Password=1234" +
            "56")]
        public string CQNDCL20180910ConnectionString {
            get {
                return ((string)(this["CQNDCL20180910ConnectionString"]));
            }
        }
    }
}
