//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3649
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEWE.CarManagement.Commons.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 balck_type 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsertBlack", ReplyAction="*")]
        EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackResponse IsertBlack(EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsertBlackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsertBlack", Namespace="http://tempuri.org/", Order=0)]
        public EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequestBody Body;
        
        public IsertBlackRequest() {
        }
        
        public IsertBlackRequest(EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsertBlackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string balck_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string balck_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string balck_indes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string balck_phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string balck_state;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int istrue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string balck_reason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string balck_remark;
        
        public IsertBlackRequestBody() {
        }
        
        public IsertBlackRequestBody(string balck_type, string balck_name, string balck_indes, string balck_phone, string balck_state, int istrue, string balck_reason, string balck_remark) {
            this.balck_type = balck_type;
            this.balck_name = balck_name;
            this.balck_indes = balck_indes;
            this.balck_phone = balck_phone;
            this.balck_state = balck_state;
            this.istrue = istrue;
            this.balck_reason = balck_reason;
            this.balck_remark = balck_remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsertBlackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsertBlackResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackResponseBody Body;
        
        public IsertBlackResponse() {
        }
        
        public IsertBlackResponse(EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsertBlackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsertBlackResult;
        
        public IsertBlackResponseBody() {
        }
        
        public IsertBlackResponseBody(string IsertBlackResult) {
            this.IsertBlackResult = IsertBlackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : EMEWE.CarManagement.Commons.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<EMEWE.CarManagement.Commons.ServiceReference1.Service1Soap>, EMEWE.CarManagement.Commons.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackResponse EMEWE.CarManagement.Commons.ServiceReference1.Service1Soap.IsertBlack(EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequest request) {
            return base.Channel.IsertBlack(request);
        }
        
        public string IsertBlack(string balck_type, string balck_name, string balck_indes, string balck_phone, string balck_state, int istrue, string balck_reason, string balck_remark) {
            EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequest inValue = new EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequest();
            inValue.Body = new EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackRequestBody();
            inValue.Body.balck_type = balck_type;
            inValue.Body.balck_name = balck_name;
            inValue.Body.balck_indes = balck_indes;
            inValue.Body.balck_phone = balck_phone;
            inValue.Body.balck_state = balck_state;
            inValue.Body.istrue = istrue;
            inValue.Body.balck_reason = balck_reason;
            inValue.Body.balck_remark = balck_remark;
            EMEWE.CarManagement.Commons.ServiceReference1.IsertBlackResponse retVal = ((EMEWE.CarManagement.Commons.ServiceReference1.Service1Soap)(this)).IsertBlack(inValue);
            return retVal.Body.IsertBlackResult;
        }
    }
}
