//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace JLMDSAP.sappwd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_pd_info_upload_reqBinding", Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class BS_CARSYS_CQ_SI_pd_info_upload_req : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_pd_info_upload_reqOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BS_CARSYS_CQ_SI_pd_info_upload_req() {
            this.Url = global::JLMDSAP.Properties.Settings.Default.JLMDSAP_sappwd_BS_CARSYS_CQ_SI_pd_info_upload_req;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_pd_info_upload_reqCompletedEventHandler SI_pd_info_upload_reqCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_pd_info_upload_res", Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
        public DT_pd_info_upload_res SI_pd_info_upload_req([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:NDPaper.com:I_QM:pd_info_upload")] [System.Xml.Serialization.XmlArrayItemAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] DT_pd_info_upload_reqRow[] MT_pd_info_upload_req) {
            object[] results = this.Invoke("SI_pd_info_upload_req", new object[] {
                        MT_pd_info_upload_req});
            return ((DT_pd_info_upload_res)(results[0]));
        }
        
        /// <remarks/>
        public void SI_pd_info_upload_reqAsync(DT_pd_info_upload_reqRow[] MT_pd_info_upload_req) {
            this.SI_pd_info_upload_reqAsync(MT_pd_info_upload_req, null);
        }
        
        /// <remarks/>
        public void SI_pd_info_upload_reqAsync(DT_pd_info_upload_reqRow[] MT_pd_info_upload_req, object userState) {
            if ((this.SI_pd_info_upload_reqOperationCompleted == null)) {
                this.SI_pd_info_upload_reqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_pd_info_upload_reqOperationCompleted);
            }
            this.InvokeAsync("SI_pd_info_upload_req", new object[] {
                        MT_pd_info_upload_req}, this.SI_pd_info_upload_reqOperationCompleted, userState);
        }
        
        private void OnSI_pd_info_upload_reqOperationCompleted(object arg) {
            if ((this.SI_pd_info_upload_reqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_pd_info_upload_reqCompleted(this, new SI_pd_info_upload_reqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_reqRow {
        
        private string i_CARNOField;
        
        private string i_VEHICLE_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_CARNO {
            get {
                return this.i_CARNOField;
            }
            set {
                this.i_CARNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_VEHICLE_TYPE {
            get {
                return this.i_VEHICLE_TYPEField;
            }
            set {
                this.i_VEHICLE_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_res {
        
        private DT_pd_info_upload_resZMMT_CPC_DAT[] zMMT_CPC_DATField;
        
        private DT_pd_info_upload_resZLET_BD_DATE[] zLET_BD_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZMMT_CPC_DAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_pd_info_upload_resZMMT_CPC_DAT[] ZMMT_CPC_DAT {
            get {
                return this.zMMT_CPC_DATField;
            }
            set {
                this.zMMT_CPC_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZLET_BD_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_pd_info_upload_resZLET_BD_DATE[] ZLET_BD_DATE {
            get {
                return this.zLET_BD_DATEField;
            }
            set {
                this.zLET_BD_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_resZMMT_CPC_DAT {
        
        private string bD_NOField;
        
        private string cARNOField;
        
        private string pzField;
        
        private string kC_DATEField;
        
        private string kC_TIMEField;
        
        private string kC_LOCATIONField;
        
        private string mzField;
        
        private string mC_DATEField;
        
        private string mC_TIMEField;
        
        private string mC_LOCATIONField;
        
        private string jzField;
        
        private string fBZLField;
        
        private string fB_DATEField;
        
        private string fB_TIMEField;
        
        private string fB_LOCATIONField;
        
        private string fHZLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BD_NO {
            get {
                return this.bD_NOField;
            }
            set {
                this.bD_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CARNO {
            get {
                return this.cARNOField;
            }
            set {
                this.cARNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PZ {
            get {
                return this.pzField;
            }
            set {
                this.pzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KC_DATE {
            get {
                return this.kC_DATEField;
            }
            set {
                this.kC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KC_TIME {
            get {
                return this.kC_TIMEField;
            }
            set {
                this.kC_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KC_LOCATION {
            get {
                return this.kC_LOCATIONField;
            }
            set {
                this.kC_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MZ {
            get {
                return this.mzField;
            }
            set {
                this.mzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MC_DATE {
            get {
                return this.mC_DATEField;
            }
            set {
                this.mC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MC_TIME {
            get {
                return this.mC_TIMEField;
            }
            set {
                this.mC_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MC_LOCATION {
            get {
                return this.mC_LOCATIONField;
            }
            set {
                this.mC_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JZ {
            get {
                return this.jzField;
            }
            set {
                this.jzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FBZL {
            get {
                return this.fBZLField;
            }
            set {
                this.fBZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_DATE {
            get {
                return this.fB_DATEField;
            }
            set {
                this.fB_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_TIME {
            get {
                return this.fB_TIMEField;
            }
            set {
                this.fB_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_LOCATION {
            get {
                return this.fB_LOCATIONField;
            }
            set {
                this.fB_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FHZL {
            get {
                return this.fHZLField;
            }
            set {
                this.fHZLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_resZLET_BD_DATE {
        
        private string mANDTField;
        
        private string bD_NOField;
        
        private string iTEMField;
        
        private string cARNOField;
        
        private string lICENSE_NUMField;
        
        private string dC_NOField;
        
        private string iNBOUND_HUField;
        
        private string bL_NOField;
        
        private string cHAUFFEURField;
        
        private string cHA_NAMEField;
        
        private string yWLXField;
        
        private string gBMSField;
        
        private string vBELN_VLField;
        
        private string eBELNField;
        
        private string bUKRSField;
        
        private string eBELPField;
        
        private string yC_WERKSField;
        
        private string sH_WERKSField;
        
        private string dBCTField;
        
        private string z_PQTIONField;
        
        private string z_RCLGORTField;
        
        private string yC_LGORTField;
        
        private string yC_LGOBEField;
        
        private string lGORTField;
        
        private string lGOBEField;
        
        private string sHDHField;
        
        private string dJ_WField;
        
        private string mgField;
        
        private string f_WField;
        
        private string f_DATEField;
        
        private string f_TIMEField;
        
        private string f_USERField;
        
        private string f_BTField;
        
        private string s_WField;
        
        private string s_DATEField;
        
        private string s_TIMEField;
        
        private string s_USERField;
        
        private string s_BTField;
        
        private string bJZField;
        
        private string qZZLField;
        
        private string wZ_FLAGField;
        
        private string rKBSField;
        
        private string dBFGZLField;
        
        private string zCBZField;
        
        private string xHBZField;
        
        private string fZBZLField;
        
        private string fZB_DATEField;
        
        private string fZB_TIMEField;
        
        private string fBZLField;
        
        private string fB_TIMEField;
        
        private string fB_DATEField;
        
        private string fB_BTField;
        
        private string fB_USERField;
        
        private string zJBZField;
        
        private string zJXXField;
        
        private string ksField;
        
        private string kzField;
        
        private string kZZField;
        
        private string bDZTField;
        
        private string rEF_BD_NOField;
        
        private string mOD_DATEField;
        
        private string mOD_TIMEField;
        
        private string mOD_USERField;
        
        private string bAKField;
        
        private string dEL_FLAGField;
        
        private string bsField;
        
        private string dBZField;
        
        private string zJBSField;
        
        private string gLPNField;
        
        private string jeField;
        
        private string xHDDField;
        
        private string zY_TYPEField;
        
        private string zYWZField;
        
        private string zCBSField;
        
        private string mATNRField;
        
        private string yCDWHField;
        
        private string zDWNRField;
        
        private string zRKJZField;
        
        private string zGRZTField;
        
        private string zRMATField;
        
        private string rBELPField;
        
        private string zFLAG_TXField;
        
        private string zHW_STATUSField;
        
        private string cONTAINERField;
        
        private string sH_LIFNRField;
        
        private string yC_ZDWNRField;
        
        private string yRDWHField;
        
        private string zJTNRField;
        
        private string mEINSField;
        
        private string pROD_CONFField;
        
        private string hGXHField;
        
        private string zCZ_CZField;
        
        private string zXZ_XZField;
        
        private string zCONF_USERField;
        
        private string zCONF_DATEField;
        
        private string zCONF_TIMEField;
        
        private string zMOD_USERField;
        
        private string zMOD_DATEField;
        
        private string zMOD_TIMEField;
        
        private string zTXDATEField;
        
        private string zTXNRField;
        
        private string zHXQKField;
        
        private string zSGNRField;
        
        private string zYTBZField;
        
        private string pRT_FLAGField;
        
        private string rG_FLAGField;
        
        private string rEF_BDNOField;
        
        private string vBELNField;
        
        private string zXHDDField;
        
        private string zLHDDField;
        
        private string zJHLXField;
        
        private string pOSNRField;
        
        private string cONTAINER1Field;
        
        private string iNBOUND_HU1Field;
        
        private string pRT_FLAG2Field;
        
        private string zTCField;
        
        private string z_CARField;
        
        private string bSTYPField;
        
        private string zHWLXField;
        
        private string sTATUSField;
        
        private string bD_TLDField;
        
        private string rOUTEField;
        
        private string z_SBCARField;
        
        private string shField;
        
        private string bLANDField;
        
        private string zCFLGField;
        
        private string rOUTE2Field;
        
        private string sPMONEYField;
        
        private string pJFLAGField;
        
        private string nOTEField;
        
        private string vNAME1Field;
        
        private string ySET1Field;
        
        private string yRSNM1Field;
        
        private string yRSNM2Field;
        
        private string ySET2Field;
        
        private string zYJQZZLField;
        
        private string zSL_USERField;
        
        private string zSL_DATEField;
        
        private string zSL_TIMEField;
        
        private DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU[] zLETBDSTRUField;
        
        private DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU_APPEND[] zLETBDSTRU_APPENDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BD_NO {
            get {
                return this.bD_NOField;
            }
            set {
                this.bD_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CARNO {
            get {
                return this.cARNOField;
            }
            set {
                this.cARNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LICENSE_NUM {
            get {
                return this.lICENSE_NUMField;
            }
            set {
                this.lICENSE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DC_NO {
            get {
                return this.dC_NOField;
            }
            set {
                this.dC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INBOUND_HU {
            get {
                return this.iNBOUND_HUField;
            }
            set {
                this.iNBOUND_HUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BL_NO {
            get {
                return this.bL_NOField;
            }
            set {
                this.bL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHAUFFEUR {
            get {
                return this.cHAUFFEURField;
            }
            set {
                this.cHAUFFEURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHA_NAME {
            get {
                return this.cHA_NAMEField;
            }
            set {
                this.cHA_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YWLX {
            get {
                return this.yWLXField;
            }
            set {
                this.yWLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GBMS {
            get {
                return this.gBMSField;
            }
            set {
                this.gBMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN_VL {
            get {
                return this.vBELN_VLField;
            }
            set {
                this.vBELN_VLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YC_WERKS {
            get {
                return this.yC_WERKSField;
            }
            set {
                this.yC_WERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SH_WERKS {
            get {
                return this.sH_WERKSField;
            }
            set {
                this.sH_WERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DBCT {
            get {
                return this.dBCTField;
            }
            set {
                this.dBCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_PQTION {
            get {
                return this.z_PQTIONField;
            }
            set {
                this.z_PQTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_RCLGORT {
            get {
                return this.z_RCLGORTField;
            }
            set {
                this.z_RCLGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YC_LGORT {
            get {
                return this.yC_LGORTField;
            }
            set {
                this.yC_LGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YC_LGOBE {
            get {
                return this.yC_LGOBEField;
            }
            set {
                this.yC_LGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGOBE {
            get {
                return this.lGOBEField;
            }
            set {
                this.lGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHDH {
            get {
                return this.sHDHField;
            }
            set {
                this.sHDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DJ_W {
            get {
                return this.dJ_WField;
            }
            set {
                this.dJ_WField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MG {
            get {
                return this.mgField;
            }
            set {
                this.mgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_W {
            get {
                return this.f_WField;
            }
            set {
                this.f_WField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_DATE {
            get {
                return this.f_DATEField;
            }
            set {
                this.f_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_TIME {
            get {
                return this.f_TIMEField;
            }
            set {
                this.f_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_USER {
            get {
                return this.f_USERField;
            }
            set {
                this.f_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_BT {
            get {
                return this.f_BTField;
            }
            set {
                this.f_BTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S_W {
            get {
                return this.s_WField;
            }
            set {
                this.s_WField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S_DATE {
            get {
                return this.s_DATEField;
            }
            set {
                this.s_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S_TIME {
            get {
                return this.s_TIMEField;
            }
            set {
                this.s_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S_USER {
            get {
                return this.s_USERField;
            }
            set {
                this.s_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S_BT {
            get {
                return this.s_BTField;
            }
            set {
                this.s_BTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BJZ {
            get {
                return this.bJZField;
            }
            set {
                this.bJZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QZZL {
            get {
                return this.qZZLField;
            }
            set {
                this.qZZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WZ_FLAG {
            get {
                return this.wZ_FLAGField;
            }
            set {
                this.wZ_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RKBS {
            get {
                return this.rKBSField;
            }
            set {
                this.rKBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DBFGZL {
            get {
                return this.dBFGZLField;
            }
            set {
                this.dBFGZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCBZ {
            get {
                return this.zCBZField;
            }
            set {
                this.zCBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XHBZ {
            get {
                return this.xHBZField;
            }
            set {
                this.xHBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FZBZL {
            get {
                return this.fZBZLField;
            }
            set {
                this.fZBZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FZB_DATE {
            get {
                return this.fZB_DATEField;
            }
            set {
                this.fZB_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FZB_TIME {
            get {
                return this.fZB_TIMEField;
            }
            set {
                this.fZB_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FBZL {
            get {
                return this.fBZLField;
            }
            set {
                this.fBZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_TIME {
            get {
                return this.fB_TIMEField;
            }
            set {
                this.fB_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_DATE {
            get {
                return this.fB_DATEField;
            }
            set {
                this.fB_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_BT {
            get {
                return this.fB_BTField;
            }
            set {
                this.fB_BTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FB_USER {
            get {
                return this.fB_USERField;
            }
            set {
                this.fB_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJBZ {
            get {
                return this.zJBZField;
            }
            set {
                this.zJBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJXX {
            get {
                return this.zJXXField;
            }
            set {
                this.zJXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KS {
            get {
                return this.ksField;
            }
            set {
                this.ksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KZ {
            get {
                return this.kzField;
            }
            set {
                this.kzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KZZ {
            get {
                return this.kZZField;
            }
            set {
                this.kZZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BDZT {
            get {
                return this.bDZTField;
            }
            set {
                this.bDZTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_BD_NO {
            get {
                return this.rEF_BD_NOField;
            }
            set {
                this.rEF_BD_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOD_DATE {
            get {
                return this.mOD_DATEField;
            }
            set {
                this.mOD_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOD_TIME {
            get {
                return this.mOD_TIMEField;
            }
            set {
                this.mOD_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOD_USER {
            get {
                return this.mOD_USERField;
            }
            set {
                this.mOD_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BAK {
            get {
                return this.bAKField;
            }
            set {
                this.bAKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_FLAG {
            get {
                return this.dEL_FLAGField;
            }
            set {
                this.dEL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BS {
            get {
                return this.bsField;
            }
            set {
                this.bsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DBZ {
            get {
                return this.dBZField;
            }
            set {
                this.dBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJBS {
            get {
                return this.zJBSField;
            }
            set {
                this.zJBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GLPN {
            get {
                return this.gLPNField;
            }
            set {
                this.gLPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JE {
            get {
                return this.jeField;
            }
            set {
                this.jeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XHDD {
            get {
                return this.xHDDField;
            }
            set {
                this.xHDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZY_TYPE {
            get {
                return this.zY_TYPEField;
            }
            set {
                this.zY_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYWZ {
            get {
                return this.zYWZField;
            }
            set {
                this.zYWZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCBS {
            get {
                return this.zCBSField;
            }
            set {
                this.zCBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YCDWH {
            get {
                return this.yCDWHField;
            }
            set {
                this.yCDWHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZDWNR {
            get {
                return this.zDWNRField;
            }
            set {
                this.zDWNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRKJZ {
            get {
                return this.zRKJZField;
            }
            set {
                this.zRKJZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZGRZT {
            get {
                return this.zGRZTField;
            }
            set {
                this.zGRZTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRMAT {
            get {
                return this.zRMATField;
            }
            set {
                this.zRMATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RBELP {
            get {
                return this.rBELPField;
            }
            set {
                this.rBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZFLAG_TX {
            get {
                return this.zFLAG_TXField;
            }
            set {
                this.zFLAG_TXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHW_STATUS {
            get {
                return this.zHW_STATUSField;
            }
            set {
                this.zHW_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTAINER {
            get {
                return this.cONTAINERField;
            }
            set {
                this.cONTAINERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SH_LIFNR {
            get {
                return this.sH_LIFNRField;
            }
            set {
                this.sH_LIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YC_ZDWNR {
            get {
                return this.yC_ZDWNRField;
            }
            set {
                this.yC_ZDWNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YRDWH {
            get {
                return this.yRDWHField;
            }
            set {
                this.yRDWHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJTNR {
            get {
                return this.zJTNRField;
            }
            set {
                this.zJTNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROD_CONF {
            get {
                return this.pROD_CONFField;
            }
            set {
                this.pROD_CONFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HGXH {
            get {
                return this.hGXHField;
            }
            set {
                this.hGXHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCZ_CZ {
            get {
                return this.zCZ_CZField;
            }
            set {
                this.zCZ_CZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZXZ_XZ {
            get {
                return this.zXZ_XZField;
            }
            set {
                this.zXZ_XZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCONF_USER {
            get {
                return this.zCONF_USERField;
            }
            set {
                this.zCONF_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCONF_DATE {
            get {
                return this.zCONF_DATEField;
            }
            set {
                this.zCONF_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCONF_TIME {
            get {
                return this.zCONF_TIMEField;
            }
            set {
                this.zCONF_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZMOD_USER {
            get {
                return this.zMOD_USERField;
            }
            set {
                this.zMOD_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZMOD_DATE {
            get {
                return this.zMOD_DATEField;
            }
            set {
                this.zMOD_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZMOD_TIME {
            get {
                return this.zMOD_TIMEField;
            }
            set {
                this.zMOD_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTXDATE {
            get {
                return this.zTXDATEField;
            }
            set {
                this.zTXDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTXNR {
            get {
                return this.zTXNRField;
            }
            set {
                this.zTXNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHXQK {
            get {
                return this.zHXQKField;
            }
            set {
                this.zHXQKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSGNR {
            get {
                return this.zSGNRField;
            }
            set {
                this.zSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYTBZ {
            get {
                return this.zYTBZField;
            }
            set {
                this.zYTBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRT_FLAG {
            get {
                return this.pRT_FLAGField;
            }
            set {
                this.pRT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RG_FLAG {
            get {
                return this.rG_FLAGField;
            }
            set {
                this.rG_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_BDNO {
            get {
                return this.rEF_BDNOField;
            }
            set {
                this.rEF_BDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZXHDD {
            get {
                return this.zXHDDField;
            }
            set {
                this.zXHDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZLHDD {
            get {
                return this.zLHDDField;
            }
            set {
                this.zLHDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJHLX {
            get {
                return this.zJHLXField;
            }
            set {
                this.zJHLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTAINER1 {
            get {
                return this.cONTAINER1Field;
            }
            set {
                this.cONTAINER1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INBOUND_HU1 {
            get {
                return this.iNBOUND_HU1Field;
            }
            set {
                this.iNBOUND_HU1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRT_FLAG2 {
            get {
                return this.pRT_FLAG2Field;
            }
            set {
                this.pRT_FLAG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTC {
            get {
                return this.zTCField;
            }
            set {
                this.zTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_CAR {
            get {
                return this.z_CARField;
            }
            set {
                this.z_CARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSTYP {
            get {
                return this.bSTYPField;
            }
            set {
                this.bSTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHWLX {
            get {
                return this.zHWLXField;
            }
            set {
                this.zHWLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BD_TLD {
            get {
                return this.bD_TLDField;
            }
            set {
                this.bD_TLDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ROUTE {
            get {
                return this.rOUTEField;
            }
            set {
                this.rOUTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Z_SBCAR {
            get {
                return this.z_SBCARField;
            }
            set {
                this.z_SBCARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SH {
            get {
                return this.shField;
            }
            set {
                this.shField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLAND {
            get {
                return this.bLANDField;
            }
            set {
                this.bLANDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCFLG {
            get {
                return this.zCFLGField;
            }
            set {
                this.zCFLGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ROUTE2 {
            get {
                return this.rOUTE2Field;
            }
            set {
                this.rOUTE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SPMONEY {
            get {
                return this.sPMONEYField;
            }
            set {
                this.sPMONEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PJFLAG {
            get {
                return this.pJFLAGField;
            }
            set {
                this.pJFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTE {
            get {
                return this.nOTEField;
            }
            set {
                this.nOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VNAME1 {
            get {
                return this.vNAME1Field;
            }
            set {
                this.vNAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YSET1 {
            get {
                return this.ySET1Field;
            }
            set {
                this.ySET1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YRSNM1 {
            get {
                return this.yRSNM1Field;
            }
            set {
                this.yRSNM1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YRSNM2 {
            get {
                return this.yRSNM2Field;
            }
            set {
                this.yRSNM2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YSET2 {
            get {
                return this.ySET2Field;
            }
            set {
                this.ySET2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYJQZZL {
            get {
                return this.zYJQZZLField;
            }
            set {
                this.zYJQZZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSL_USER {
            get {
                return this.zSL_USERField;
            }
            set {
                this.zSL_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSL_DATE {
            get {
                return this.zSL_DATEField;
            }
            set {
                this.zSL_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSL_TIME {
            get {
                return this.zSL_TIMEField;
            }
            set {
                this.zSL_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZLETBDSTRU", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU[] ZLETBDSTRU {
            get {
                return this.zLETBDSTRUField;
            }
            set {
                this.zLETBDSTRUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZLETBDSTRU_APPEND", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU_APPEND[] ZLETBDSTRU_APPEND {
            get {
                return this.zLETBDSTRU_APPENDField;
            }
            set {
                this.zLETBDSTRU_APPENDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU {
        
        private string yRSDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YRSDAT {
            get {
                return this.yRSDATField;
            }
            set {
                this.yRSDATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NDPaper.com:I_QM:pd_info_upload")]
    public partial class DT_pd_info_upload_resZLET_BD_DATEZLETBDSTRU_APPEND {
        
        private string lOADER_NOField;
        
        private string lOADER_NAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOADER_NO {
            get {
                return this.lOADER_NOField;
            }
            set {
                this.lOADER_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOADER_NAME {
            get {
                return this.lOADER_NAMEField;
            }
            set {
                this.lOADER_NAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SI_pd_info_upload_reqCompletedEventHandler(object sender, SI_pd_info_upload_reqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_pd_info_upload_reqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_pd_info_upload_reqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_pd_info_upload_res Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_pd_info_upload_res)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591